# NOTE: DOCUMENTATION - this goes on the server only 
# and doesn't get used anywhere else
services:
  imgthemer:
    image: ghcr.io/mikayil-dev/imgthemer:latest
    container_name: imgthemer
    restart: unless-stopped
    ports:
      - "127.0.0.1:4321:4321"
